"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.batchSpace = exports.cloudSpace = exports.testSpace = exports.mergeSpace = exports.patchSpace = exports.runSpace = exports.openSpace = exports.editSpace = exports.readySpace = exports.updateSpace = exports.initSpace = void 0;
var space_buzz_1 = require("./buz/space.buzz");
Object.defineProperty(exports, "initSpace", { enumerable: true, get: function () { return space_buzz_1.initSpace; } });
var space_buzz_2 = require("./buz/space.buzz");
Object.defineProperty(exports, "updateSpace", { enumerable: true, get: function () { return space_buzz_2.updateSpace; } });
var space_buzz_3 = require("./buz/space.buzz");
Object.defineProperty(exports, "readySpace", { enumerable: true, get: function () { return space_buzz_3.readySpace; } });
var space_buzz_4 = require("./buz/space.buzz");
Object.defineProperty(exports, "editSpace", { enumerable: true, get: function () { return space_buzz_4.editSpace; } });
var space_buzz_5 = require("./buz/space.buzz");
Object.defineProperty(exports, "openSpace", { enumerable: true, get: function () { return space_buzz_5.openSpace; } });
var space_buzz_6 = require("./buz/space.buzz");
Object.defineProperty(exports, "runSpace", { enumerable: true, get: function () { return space_buzz_6.runSpace; } });
var space_buzz_7 = require("./buz/space.buzz");
Object.defineProperty(exports, "patchSpace", { enumerable: true, get: function () { return space_buzz_7.patchSpace; } });
var space_buzz_8 = require("./buz/space.buzz");
Object.defineProperty(exports, "mergeSpace", { enumerable: true, get: function () { return space_buzz_8.mergeSpace; } });
var space_buzz_9 = require("./buz/space.buzz");
Object.defineProperty(exports, "testSpace", { enumerable: true, get: function () { return space_buzz_9.testSpace; } });
var space_buzz_10 = require("./buz/space.buzz");
Object.defineProperty(exports, "cloudSpace", { enumerable: true, get: function () { return space_buzz_10.cloudSpace; } });
var space_buzz_11 = require("./buz/space.buzz");
Object.defineProperty(exports, "batchSpace", { enumerable: true, get: function () { return space_buzz_11.batchSpace; } });
//# sourceMappingURL=space.buzzer.js.map